# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_name', models.CharField(max_length=20)),
                ('goal_amount', models.IntegerField()),
                ('amount_collected', models.IntegerField()),
            ],
        ),
    ]
