# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0003_carouselevents_messagebar'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxWidgets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('active', models.BooleanField()),
                ('order', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)])),
                ('content', models.TextField(max_length=4096)),
            ],
        ),
    ]
